ifneq ($(LOCAL_PRECOMPILE_HEADER),)
LOCAL_PRECOMPILE_HEADER_GCH := $(LOCAL_PRECOMPILE_HEADER).gch
LOCAL_PRECOMPILE_HEADER_DEP := $(LOCAL_PRECOMPILE_HEADER).d
EXT_TARGET_LIST += $(LOCAL_PRECOMPILE_HEADER_GCH) 
EXT_TARGET_LIST += $(LOCAL_PRECOMPILE_HEADER_DEP)

LOCAL_PRE_COMPILE_FLAGS := -include $(LOCAL_PRECOMPILE_HEADER)
CPPFLAGS += $(LOCAL_PRE_COMPILE_FLAGS)
CPPFLAGS_$(LOCAL_MODULE) += -Winvalid-pch -include $(LOCAL_PRECOMPILE_HEADER)
CPPFLAGS_$(LOCAL_PRECOMPILE_HEADER_DEP) := $(CPPFLAGS) $(CPPFLAGS_$(LOCAL_MODULE))
CPPFLAGS_$(LOCAL_PRECOMPILE_HEADER_GCH) := $(CPPFLAGS) $(CPPFLAGS_$(LOCAL_MODULE))
CXXFLAGS_$(LOCAL_PRECOMPILE_HEADER_GCH) := $(CXXFLAGS)

-include $(LOCAL_PRECOMPILE_HEADER).d
$(LOCAL_PRECOMPILE_HEADER_DEP):$(LOCAL_PRECOMPILE_HEADER)
	@mkdir -p $(shell dirname $@)
	@$(CPP) $(CPPFLAGS_$@) -MF"$@" -MM -MP -MT"$(@:.d=.gch)" $<

$(LOCAL_PRECOMPILE_HEADER_GCH):$(LOCAL_PRECOMPILE_HEADER) $(LOCAL_PRECOMPILE_HEADER_DEP)
	@$(CXX) $(CPPFLAGS_$@) $(CXXFLAGS_$@) -o $@ $<
	@$(call AddObj," GEN","Generate Precompile header")
endif
